#! /usr/bin/bash

echo " start compiling "

case $1 in


a)   
    cl65 -C $2.cfg -Ln $2.lbl -l $2.lst -m $2.map \
    --debug-info --cpu 6502 -t none --no-target-lib \
    -o $2.rom \
    $2.s 2> err | tee out

    mv $2.bin $2.rom
    od --endian=big -x < $2.rom > $2.bhx


    ;;


x)
    rm $2.obj $2.dep $2.asm $2.map $2.lbl $2.lst $2.ram $2.rom
    rm out err *.bin *.bhx 
    
    ;;

esac

echo " stop compiling "



